# The goal of this R script is to add winter variables to the clutch size data

# Activate packages
library(data.table) #for data manipulation and visuals
library(tidyverse) #helps to handle and transform data


# 1. Load clutch size data and weather data.
clutch_data <- read.csv("clutch_size/data/clutch_data_2.csv", header = TRUE)
wx <- read.csv("nest_survival/data/ice_wx.csv", header = TRUE) #this only goes up to 2019
wx2 <- read.csv("sea_ice_bs_core/output/sea_ice_vars_1979_2020.csv") # we grab 2020 ice data from here


# 1.2 remove all rows that with any NA values from dataframe
clutch_data <- na.omit(clutch_data)

# 2. Add weather variables (win_hi) using ifelse statements
clutch_data$win_hi <- ifelse(clutch_data$year == 1994,46,
                             ifelse(clutch_data$year == 1995,79,
                                    ifelse(clutch_data$year == 1996,55,
                                           ifelse(clutch_data$year == 1997,39,
                                                  ifelse(clutch_data$year == 1998,63,
                                                         ifelse(clutch_data$year == 1999,57,
                                                                ifelse(clutch_data$year == 2000,73,
                                                                       ifelse(clutch_data$year == 2001,0,
                                                                              ifelse(clutch_data$year == 2002,51,
                                                                                     ifelse(clutch_data$year == 2003,35,
                                                                                            ifelse(clutch_data$year == 2004,42,
                                                                                                   ifelse(clutch_data$year == 2005,25,
                                                                                                          ifelse(clutch_data$year == 2006,79,
                                                                                                                 ifelse(clutch_data$year == 2007,53,
                                                                                                                        ifelse(clutch_data$year == 2008,46,
                                                                                                                               ifelse(clutch_data$year == 2009,54,
                                                                                                                                      ifelse(clutch_data$year == 2010,65,
                                                                                                                                             ifelse(clutch_data$year == 2011,51,
                                                                                                                                                    ifelse(clutch_data$year == 2012,52,
                                                                                                                                                           ifelse(clutch_data$year == 2013,57,
                                                                                                                                                                  ifelse(clutch_data$year == 2014,38,
                                                                                                                                                                         ifelse(clutch_data$year == 2015,14,
                                                                                                                                                                                ifelse(clutch_data$year == 2016,11,
                                                                                                                                                                                       ifelse(clutch_data$year == 2017,28,
                                                                                                                                                                                              ifelse(clutch_data$year == 2018,0,
                                                                                                                                                                                                     ifelse(clutch_data$year == 2019,2,
                                                                                                                                                                                                            ifelse(clutch_data$year == 2021,44,0)))))))))))))))))))))))))))

# 3. Add weather variables (spr_hi)
clutch_data$spr_hi <- ifelse(clutch_data$year == 1994,9,
                             ifelse(clutch_data$year == 1995,7,
                                    ifelse(clutch_data$year == 1996,5,
                                           ifelse(clutch_data$year == 1997,13,
                                                  ifelse(clutch_data$year == 1998,11,
                                                         ifelse(clutch_data$year == 1999,18,
                                                                ifelse(clutch_data$year == 2000,10,
                                                                       ifelse(clutch_data$year == 2001,10,
                                                                              ifelse(clutch_data$year == 2002,18,
                                                                                     ifelse(clutch_data$year == 2003,9,
                                                                                            ifelse(clutch_data$year == 2004,3,
                                                                                                   ifelse(clutch_data$year == 2005,13,
                                                                                                          ifelse(clutch_data$year == 2006,11,
                                                                                                                 ifelse(clutch_data$year == 2007,10,
                                                                                                                        ifelse(clutch_data$year == 2008,27,
                                                                                                                               ifelse(clutch_data$year == 2009,23,
                                                                                                                                      ifelse(clutch_data$year == 2010,29,
                                                                                                                                             ifelse(clutch_data$year == 2011,10,
                                                                                                                                                    ifelse(clutch_data$year == 2012,23,
                                                                                                                                                           ifelse(clutch_data$year == 2013,22,
                                                                                                                                                                  ifelse(clutch_data$year == 2014,7,
                                                                                                                                                                         ifelse(clutch_data$year == 2015,7,
                                                                                                                                                                                ifelse(clutch_data$year == 2016,4,
                                                                                                                                                                                       ifelse(clutch_data$year == 2017,2,
                                                                                                                                                                                              ifelse(clutch_data$year == 2018,0,
                                                                                                                                                                                                     ifelse(clutch_data$year == 2019,0,
                                                                                                                                                                                                            ifelse(clutch_data$year == 2021,17,0)))))))))))))))))))))))))))

# 4. Add weather variables (wxt)
clutch_data$wxt <- ifelse(clutch_data$year == 1994,14,
                          ifelse(clutch_data$year == 1995,13,
                                 ifelse(clutch_data$year == 1996,6,
                                        ifelse(clutch_data$year == 1997,5,
                                               ifelse(clutch_data$year == 1998,9,
                                                      ifelse(clutch_data$year == 1999,6,
                                                             ifelse(clutch_data$year == 2000,15,
                                                                    ifelse(clutch_data$year == 2001,0,
                                                                           ifelse(clutch_data$year == 2002,19,
                                                                                  ifelse(clutch_data$year == 2003,0,
                                                                                         ifelse(clutch_data$year == 2004,0,
                                                                                                ifelse(clutch_data$year == 2005,0,
                                                                                                       ifelse(clutch_data$year == 2006,10,
                                                                                                              ifelse(clutch_data$year == 2007,14,
                                                                                                                     ifelse(clutch_data$year == 2008,19,
                                                                                                                            ifelse(clutch_data$year == 2009,21,
                                                                                                                                   ifelse(clutch_data$year == 2010,23,
                                                                                                                                          ifelse(clutch_data$year == 2011,1,
                                                                                                                                                 ifelse(clutch_data$year == 2012,36,
                                                                                                                                                        ifelse(clutch_data$year == 2013,14,
                                                                                                                                                               ifelse(clutch_data$year == 2014,5,
                                                                                                                                                                      ifelse(clutch_data$year == 2015,0,
                                                                                                                                                                             ifelse(clutch_data$year == 2016,0,
                                                                                                                                                                                    ifelse(clutch_data$year == 2017,3,
                                                                                                                                                                                           ifelse(clutch_data$year == 2018,0,
                                                                                                                                                                                                  ifelse(clutch_data$year == 2019,0,
                                                                                                                                                                                                         ifelse(clutch_data$year == 2021,17,0)))))))))))))))))))))))))))
# 5. Add weather variables (sxt)
clutch_data$sxt <- ifelse(clutch_data$year == 1994,1,
                          ifelse(clutch_data$year == 1995,5,
                                 ifelse(clutch_data$year == 1996,2,
                                        ifelse(clutch_data$year == 1997,1,
                                               ifelse(clutch_data$year == 1998,0,
                                                      ifelse(clutch_data$year == 1999,2,
                                                             ifelse(clutch_data$year == 2000,0,
                                                                    ifelse(clutch_data$year == 2001,0,
                                                                           ifelse(clutch_data$year == 2002,0,
                                                                                  ifelse(clutch_data$year == 2003,0,
                                                                                         ifelse(clutch_data$year == 2004,4,
                                                                                                ifelse(clutch_data$year == 2005,1,
                                                                                                       ifelse(clutch_data$year == 2006,1,
                                                                                                              ifelse(clutch_data$year == 2007,0,
                                                                                                                     ifelse(clutch_data$year == 2008,4,
                                                                                                                            ifelse(clutch_data$year == 2009,5,
                                                                                                                                   ifelse(clutch_data$year == 2010,5,
                                                                                                                                          ifelse(clutch_data$year == 2011,3,
                                                                                                                                                 ifelse(clutch_data$year == 2012,5,
                                                                                                                                                        ifelse(clutch_data$year == 2013,7,
                                                                                                                                                               ifelse(clutch_data$year == 2014,0,
                                                                                                                                                                      ifelse(clutch_data$year == 2015,0,
                                                                                                                                                                             ifelse(clutch_data$year == 2016,0,
                                                                                                                                                                                    ifelse(clutch_data$year == 2017,0,
                                                                                                                                                                                           ifelse(clutch_data$year == 2018,0,
                                                                                                                                                                                                  ifelse(clutch_data$year == 2019,0,
                                                                                                                                                                                                         ifelse(clutch_data$year == 2021,0,0)))))))))))))))))))))))))))

# 6. Add weather variables (wxw)
clutch_data$wxw <- ifelse(clutch_data$year == 1994,7,
                          ifelse(clutch_data$year == 1995,9,
                                 ifelse(clutch_data$year == 1996,8,
                                        ifelse(clutch_data$year == 1997,6,
                                               ifelse(clutch_data$year == 1998,4,
                                                      ifelse(clutch_data$year == 1999,7,
                                                             ifelse(clutch_data$year == 2000,6,
                                                                    ifelse(clutch_data$year == 2001,11,
                                                                           ifelse(clutch_data$year == 2002,14,
                                                                                  ifelse(clutch_data$year == 2003,3,
                                                                                         ifelse(clutch_data$year == 2004,7,
                                                                                                ifelse(clutch_data$year == 2005,5,
                                                                                                       ifelse(clutch_data$year == 2006,8,
                                                                                                              ifelse(clutch_data$year == 2007,6,
                                                                                                                     ifelse(clutch_data$year == 2008,6,
                                                                                                                            ifelse(clutch_data$year == 2009,8,
                                                                                                                                   ifelse(clutch_data$year == 2010,5,
                                                                                                                                          ifelse(clutch_data$year == 2011,7,
                                                                                                                                                 ifelse(clutch_data$year == 2012,11,
                                                                                                                                                        ifelse(clutch_data$year == 2013,8,
                                                                                                                                                               ifelse(clutch_data$year == 2014,9,
                                                                                                                                                                      ifelse(clutch_data$year == 2015,11,
                                                                                                                                                                             ifelse(clutch_data$year == 2016,8,
                                                                                                                                                                                    ifelse(clutch_data$year == 2017,7,
                                                                                                                                                                                           ifelse(clutch_data$year == 2018,9,
                                                                                                                                                                                                  ifelse(clutch_data$year == 2019,11,
                                                                                                                                                                                                         ifelse(clutch_data$year == 2021,4,0)))))))))))))))))))))))))))

# 7. Add weather variables (sxw)
clutch_data$sxw <- ifelse(clutch_data$year == 1994,1,
                          ifelse(clutch_data$year == 1995,1,
                                 ifelse(clutch_data$year == 1996,3,
                                        ifelse(clutch_data$year == 1997,0,
                                               ifelse(clutch_data$year == 1998,2,
                                                      ifelse(clutch_data$year == 1999,1,
                                                             ifelse(clutch_data$year == 2000,0,
                                                                    ifelse(clutch_data$year == 2001,3,
                                                                           ifelse(clutch_data$year == 2002,2,
                                                                                  ifelse(clutch_data$year == 2003,3,
                                                                                         ifelse(clutch_data$year == 2004,2,
                                                                                                ifelse(clutch_data$year == 2005,3,
                                                                                                       ifelse(clutch_data$year == 2006,3,
                                                                                                              ifelse(clutch_data$year == 2007,1,
                                                                                                                     ifelse(clutch_data$year == 2008,0,
                                                                                                                            ifelse(clutch_data$year == 2009,2,
                                                                                                                                   ifelse(clutch_data$year == 2010,1,
                                                                                                                                          ifelse(clutch_data$year == 2011,5,
                                                                                                                                                 ifelse(clutch_data$year == 2012,0,
                                                                                                                                                        ifelse(clutch_data$year == 2013,1,
                                                                                                                                                               ifelse(clutch_data$year == 2014,1,
                                                                                                                                                                      ifelse(clutch_data$year == 2015,2,
                                                                                                                                                                             ifelse(clutch_data$year == 2016,1,
                                                                                                                                                                                    ifelse(clutch_data$year == 2017,1,
                                                                                                                                                                                           ifelse(clutch_data$year == 2018,1,
                                                                                                                                                                                                  ifelse(clutch_data$year == 2019,2,
                                                                                                                                                                                                         ifelse(clutch_data$year == 2021,2,0)))))))))))))))))))))))))))


# 7. Add weather variables (wsi)
clutch_data$wsi <- ifelse(clutch_data$year == 1994,127.995,
                          ifelse(clutch_data$year == 1995,260.7111,
                                 ifelse(clutch_data$year == 1996,186.6333,
                                        ifelse(clutch_data$year == 1997,109.6980,
                                               ifelse(clutch_data$year == 1998,221.2001,
                                                      ifelse(clutch_data$year == 1999,211.5554,
                                                             ifelse(clutch_data$year == 2000,202.98193,
                                                                    ifelse(clutch_data$year == 2001,12.47665,
                                                                           ifelse(clutch_data$year == 2002,183.05771,
                                                                                  ifelse(clutch_data$year == 2003,114.3570,
                                                                                         ifelse(clutch_data$year == 2004,117.5891,
                                                                                                ifelse(clutch_data$year == 2005,72.01128,
                                                                                                       ifelse(clutch_data$year == 2006,269.70536,
                                                                                                              ifelse(clutch_data$year == 2007,173.8957,
                                                                                                                     ifelse(clutch_data$year == 2008,203.2355,
                                                                                                                            ifelse(clutch_data$year == 2009,196.5152,
                                                                                                                                   ifelse(clutch_data$year == 2010,319.1589,
                                                                                                                                          ifelse(clutch_data$year == 2011,197.1181,
                                                                                                                                                 ifelse(clutch_data$year == 2012,212.8251,
                                                                                                                                                        ifelse(clutch_data$year == 2013,226.8777,
                                                                                                                                                               ifelse(clutch_data$year == 2014,93.52840,
                                                                                                                                                                      ifelse(clutch_data$year == 2015,38.798337,
                                                                                                                                                                             ifelse(clutch_data$year == 2016,16.818982,
                                                                                                                                                                                    ifelse(clutch_data$year == 2017,85.154027,
                                                                                                                                                                                           ifelse(clutch_data$year == 2018,0,
                                                                                                                                                                                                  ifelse(clutch_data$year == 2019,1.386294,
                                                                                                                                                                                                         ifelse(clutch_data$year == 2021,151.115282,0)))))))))))))))))))))))))))

### 8. write the csv file in the data folder
write.csv(clutch_data, "clutch_size/data/clutch_wx.csv")

